dist: trusty
language: node_js
node_js:
  - "8.9.3"
sudo: false

branches:
  only:
    - dev

install:
  - npm i

script:
  - npm run build-dev

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_RISKMAP_US
    region: $AWS_S3_BUCKET_REGION_RISKMAP_US
    skip_cleanup: true
    local_dir: dist/dev-us
    on:
      branch: dev
